<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="ReactiveUI" Version="20.2.45" />
      <PackageReference Include="ReactiveUI.Fody" Version="19.5.41" />
      <PackageReference Include="SixLabors.ImageSharp" Version="3.1.8" />
    </ItemGroup>

    <ItemGroup>
      <None Update="Assets\Palletes\Default.pal">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Assets\Palletes\Palette.pal">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Assets\Palletes\Rainbows.pal">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Assets\Palletes\Stylish.pal">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Assets\Palletes\TrueCol.pal">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\..\data\Palletes\Default.pal">
        <Link>Palletes\Default.pal</Link>
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="..\..\data\Palletes\Palette.pal">
        <Link>Palletes\Palette.pal</Link>
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="..\..\data\Palletes\Rainbows.pal">
        <Link>Palletes\Rainbows.pal</Link>
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="..\..\data\Palletes\Stylish.pal">
        <Link>Palletes\Stylish.pal</Link>
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="..\..\data\Palletes\TrueCol.pal">
        <Link>Palletes\TrueCol.pal</Link>
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
    </ItemGroup>

</Project>
