<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
        <PackageReference Include="coverlet.collector" Version="6.0.4">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.0" />
        <PackageReference Include="NUnit" Version="4.4.0" />
        <PackageReference Include="NUnit.Analyzers" Version="4.11.1">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="NUnit3TestAdapter" Version="6.0.0-beta.1" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="NUnit.Framework"/>
    </ItemGroup>

    <ItemGroup>
      <None Update="Palletes\Palette.pal">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Palletes\Stylish.pal">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Mdt\Fe_#1_Th=65nm_2024.03.31_0.mdt">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Mdt\Fe_#1_Th=65nm_2024.04.04_0.mdt">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Mdt\Fe_#2_Th=80nm_2024.03.21_0.mdt">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Palletes\Default.pal">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Palletes\Rainbows.pal">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Palletes\TrueCol.pal">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Mdt\вах 14 минут.mdt">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\NEXUS.Parsers.MDT\NEXUS.Parsers.MDT.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\..\data\Mdt\2024.10.12_Mo_80.mdt">
        <Link>Mdt\2024.10.12_Mo_80.mdt</Link>
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="..\..\data\Mdt\2024.10.29_Mo90.mdt">
        <Link>Mdt\2024.10.29_Mo90.mdt</Link>
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="..\..\data\Mdt\2024.10.29_Mo_65.mdt">
        <Link>Mdt\2024.10.29_Mo_65.mdt</Link>
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="..\..\data\Mdt\2024.10.29_Mo_80.mdt">
        <Link>Mdt\2024.10.29_Mo_80.mdt</Link>
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="..\..\data\Mdt\2024.10.30_Mo90.mdt">
        <Link>Mdt\2024.10.30_Mo90.mdt</Link>
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="..\..\data\Mdt\3д титан.mdt">
        <Link>Mdt\3д титан.mdt</Link>
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="..\..\data\Mdt\brotli.mdt">
        <Link>Mdt\brotli.mdt</Link>
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="..\..\data\Mdt\Fe.mdt">
        <Link>Mdt\Fe.mdt</Link>
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="..\..\data\Mdt\Fe_#1_Th=65nm_2024.03.31_0.mdt">
        <Link>Mdt\Fe_#1_Th=65nm_2024.03.31_0.mdt</Link>
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="..\..\data\Mdt\Fe_#1_Th=65nm_2024.04.04_0.mdt">
        <Link>Mdt\Fe_#1_Th=65nm_2024.04.04_0.mdt</Link>
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="..\..\data\Mdt\Fe_#2_Th=80nm_2024.03.21_0.mdt">
        <Link>Mdt\Fe_#2_Th=80nm_2024.03.21_0.mdt</Link>
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="..\..\data\Mdt\Fe_#3_Th=90nm_2024.05.18_1.mdt">
        <Link>Mdt\Fe_#3_Th=90nm_2024.05.18_1.mdt</Link>
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="..\..\data\Mdt\Fe_2022.11.03_0 mod.mdt">
        <Link>Mdt\Fe_2022.11.03_0 mod.mdt</Link>
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="..\..\data\Mdt\Mo80 12 10 24 (17,5.bcr">
        <Link>Mdt\Mo80 12 10 24 (17,5.bcr</Link>
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="..\..\data\Mdt\Mo_90_2024.05.20_0.mdt">
        <Link>Mdt\Mo_90_2024.05.20_0.mdt</Link>
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="..\..\data\Mdt\Mo_90_2024.06.28_0.mdt">
        <Link>Mdt\Mo_90_2024.06.28_0.mdt</Link>
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="..\..\data\Mdt\Ti110 1000.mdt">
        <Link>Mdt\Ti110 1000.mdt</Link>
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="..\..\data\Mdt\Ti110 500.mdt">
        <Link>Mdt\Ti110 500.mdt</Link>
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="..\..\data\Mdt\Ti65 500.mdt">
        <Link>Mdt\Ti65 500.mdt</Link>
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="..\..\data\Mdt\Ti65_1000.mdt">
        <Link>Mdt\Ti65_1000.mdt</Link>
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="..\..\data\Mdt\Ti90 1000.mdt">
        <Link>Mdt\Ti90 1000.mdt</Link>
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="..\..\data\Mdt\Ti90 500.mdt">
        <Link>Mdt\Ti90 500.mdt</Link>
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="..\..\data\Mdt\вах 14 минут.mdt">
        <Link>Mdt\вах 14 минут.mdt</Link>
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="..\..\data\Mdt\Молибден.mdt">
        <Link>Mdt\Молибден.mdt</Link>
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="..\..\data\Palletes\Default.pal">
        <Link>Palletes\Default.pal</Link>
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="..\..\data\Palletes\Palette.pal">
        <Link>Palletes\Palette.pal</Link>
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="..\..\data\Palletes\Rainbows.pal">
        <Link>Palletes\Rainbows.pal</Link>
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="..\..\data\Palletes\Stylish.pal">
        <Link>Palletes\Stylish.pal</Link>
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="..\..\data\Palletes\TrueCol.pal">
        <Link>Palletes\TrueCol.pal</Link>
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
    </ItemGroup>

</Project>
