<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector" Version="6.0.4">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.13.0" />
        <PackageReference Include="NUnit" Version="4.3.2" />
        <PackageReference Include="NUnit.Analyzers" Version="4.7.0">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="NUnit3TestAdapter" Version="5.0.0" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="NUnit.Framework"/>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Bcr\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\NEXUS.Parsers.BCR\NEXUS.Parsers.BCR.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Update="Bcr\1.bcrf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\2.bcrf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Fe 1.bcrf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Fe 2.bcrf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Fe65 1 03 2024 (34.2).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Fe65 1 03 2024 (38.8).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Fe65 1 03 2024 (181.2).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Fe65 21 02 2024 (132).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Fe65 21 02 2024 (255).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Fe65 22 02 2024 (94.1).bcr">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Fe65 22 02 2024 (128).bcr">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Fe65 22 02 2024 (184).bcr">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Fe65 23 02 2024 (68.4).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Fe65 23 02 2024 (69.7).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Fe65 23 02 2024 (79.4).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Fe65 23 02 2024 (89).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Fe65 26 02 2024 (36.0).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Fe65 26 02 2024 (67.2).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Fe65 26 02 2024 (70.1.bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Fe65 26 02 2024 (134.7).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Fe65 27 02 2024 (21.7).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Fe65 27 02 2024 (36.4).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Fe65 27 02 2024 (36.44).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Fe65 27 02 2024 (46.5).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Fe65 27 02 2024 (48.4).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Fe65 27 02 2024 (53.5).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Fe65 27 02 2024 (63.3).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Fe65 28 02 2024 (17.2).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Fe65 28 02 2024 (18.8).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Fe65 28 02 2024 (31.5).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Fe65 28 02 2024 (81.3).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Fe65 28 02 2024 (175.8).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Fe80 19 02 2024 (29.5).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Fe80 19 02 2024 (30.7).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Fe80 19 02 2024 (34.8).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Fe80 19 02 2024 (37.6.bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Fe80 19 02 2024 (41.5).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Fe80 19 02 2024 (52.7).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Fe80 19 02 2024 (55.5).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Fe80 19 02 2024 (71.8).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Fe80 19 02 2024 (73.8).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Fe80 19 02 2024 (74).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Fe80 19 02 2024 (76.6).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Fe80 19 02 2024 (79.1).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Fe80 19 02 2024 (80.3).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Fe80 19 02 2024 (82.9).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Fe80 19 02 2024 (84.5).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Fe80 19 02 2024 (89.5).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Fe80 19 02 2024 (91.7).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Fe80 19 02 2024 (105).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Fe80 19 02 2024 (156).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Fe80 20 02 2024 (25.5).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Fe80 20 02 2024 (29.6).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Fe80 20 02 2024 (41.8).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Fe80 20 02 2024 (46.4).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Fe80 20 02 2024 (49.5).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Fe80 20 02 2024 (51.4).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Fe80 20 02 2024 (54.6).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Fe80 20 02 2024 (56.bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Fe80 20 02 2024 (58.7).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Fe80 20 02 2024 (58.9).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Fe80 20 02 2024 (64.9).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Fe80 20 02 2024 (69.1).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Fe80 20 02 2024 (74.5).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Fe90 16 02 2024 (19).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Fe90 16 02 2024 (23.6).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Fe90 16 02 2024 (25.9).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Fe90 16 02 2024 (26.6).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Fe90 16 02 2024 (28.9).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Fe90 16 02 2024 (30.9).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Fe90 16 02 2024 (35.6).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Fe90 16 02 2024 (36.9).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Fe90 16 02 2024 (46).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Fe90 16 02 2024 (49.4).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Fe90 16 02 2024 (50.4).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Fe90 16 02 2024 (60.6).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Fe90 16 02 2024 (64.6).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Fe90 16 02 2024 (79).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Fe90 16 02 2024 (83.5).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Fe90 16 02 2024 (90).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Fe90 16 02 2024 (135.4).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Fe90 16 02 2024 (220).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Fe 2000 14 02 2024 (36).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Fe 2000 14 02 2024 (49).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Fe 2000 14 02 2024 (61).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Fe 2000 14 02 2024 (178).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Fe 2000 14 02 2024 (278).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Mo 1.bcrf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Mo 2.bcrf">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Mo65 11 10 24 (11,6).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Mo65 11 10 24 (19).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Mo65 11 10 24 (20,6).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Mo65 11 10 24 (21).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Mo65 11 10 24 (21,4).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Mo65 11 10 24 (21,45).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Mo65 11 10 24 (24).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Mo65 11 10 24 (43).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Mo65 12 10 24 (10,3).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Mo65 12 10 24 (15,2).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Mo65 12 10 24 (15,7).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Mo65 12 10 24 (17,5).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Mo65 12 10 24 (21,2).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Mo65 12 10 24 (22,9).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Mo65 12 10 24 (23,5).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Mo65 12 10 24 (30,8).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Mo65 12 10 24 (36,7).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Mo65 12 10 24 (51,3).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Mo65 12 10 24 (59,5).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Mo65 12 10 24 (77,8).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Mo65 12 10 24 (148,3).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Mo80 11 10 24 (18).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Mo80 11 10 24 (20).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Mo80 11 10 24 (20,2).bcr">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Mo80 11 10 24 (21,7).bcr">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Mo80 11 10 24 (22).bcr">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Mo80 11 10 24 (28,4).bcr">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Mo80 11 10 24 (28,8).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Mo80 12 10 24 (15,4).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Mo80 12 10 24 (15,7).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Mo80 12 10 24 (17,4).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Mo80 12 10 24 (17,5.bcr">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Mo80 12 10 24 (18,5).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Mo80 12 10 24 (25,3).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Mo80 12 10 24 (26,2).bcr">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Mo80 12 10 24 (26,5).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Mo80 12 10 24 (27,7).bcr">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Mo80 12 10 24 (28,41).bcr">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Mo80 12 10 24 (32).bcr">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Bcr\Mo80 12 10 24 (35,5).bcr">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
    </ItemGroup>

</Project>
