namespace NEXUS.MDT.Enums;

public enum SpmMode
{
    ConstantForce = 0,
    ContactConstantHeight = 1,
    ContactError = 2,
    LateralForce = 3,
    ForceModulation = 4,
    SpreadingResistanceImaging = 5,
    SemicontactTopography = 6,
    SemicontactError = 7,
    PhaseContrast = 8,
    AcMagneticForce = 9,
    DcMagneticForce = 10,
    ElectrostaticForce = 11,
    CapacitanceContrast = 12,
    KelvinProbe = 13,
    ConstantCurrent = 14,
    BarrierHeight = 15,
    ConstantHeight = 16,
    Afam = 17,
    ContactEfm = 18,
    ShearForceTopography = 19,
    Sfom = 20,
    ContactCapacitance = 21,
    SnomTransmission = 22,
    SnomReflection = 23,
    SnomAll = 24,
    Snom = 25,
}