name: NEXUS DESKTOP

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  create-release:
    runs-on: windows-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract version from tag
        id: extract-version
        shell: pwsh
        run: |
          $version = $env:GITHUB_REF -replace "refs/tags/v", ""
          echo "version=$version" >> $env:GITHUB_OUTPUT
          Write-Host "Extracted version: $version"

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      
      # Fractal
      - name: Build NEXUS.Fractal
        shell: pwsh
        run: |
          dotnet publish NEXUS.Fractal -c Release -r win-x64 --self-contained true `
            -p:PublishSingleFile=true -p:IncludeAllContentForSelfExtract=true `
            -o ./artifacts/Fractal

      - name: Create Fractal ZIP
        shell: pwsh
        run: |
          $version = "${{ steps.extract-version.outputs.version }}"
          Compress-Archive -Path ./artifacts/Fractal/* -DestinationPath "./NEXUS.Fractal-$version.zip"
      
      # Growth
      - name: Build NEXUS.Growth
        shell: pwsh
        run: |
          dotnet publish NEXUS.Growth -c Release -r win-x64 --self-contained true `
            -p:PublishSingleFile=true -p:IncludeAllContentForSelfExtract=true `
            -o ./artifacts/Growth

      - name: Create Growth ZIP
        shell: pwsh
        run: |
          $version = "${{ steps.extract-version.outputs.version }}"
          Compress-Archive -Path ./artifacts/Growth/* -DestinationPath "./NEXUS.Growth-$version.zip"
      
      # Simulation
      - name: Build NEXUS.Growth.Simulation
        shell: pwsh
        run: |
          dotnet publish NEXUS.Growth.Simulation -c Release -r win-x64 --self-contained true `
            -p:PublishSingleFile=true -p:IncludeAllContentForSelfExtract=true `
            -o ./artifacts/Simulation

      - name: Create Simulation ZIP
        shell: pwsh
        run: |
          $version = "${{ steps.extract-version.outputs.version }}"
          Compress-Archive -Path ./artifacts/Simulation/* -DestinationPath "./NEXUS.Growth.Simulation-$version.zip"

      - name: Create GitHub Release
        id: create-release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          name: NEXUS ${{ steps.extract-version.outputs.version }}
          body: |
            NEXUS Desktop Applications Release ${{ steps.extract-version.outputs.version }}
            
            Includes:
            - NEXUS.Fractal (Avalonia)
            - NEXUS.Growth (Avalonia)
            - NEXUS.Growth.Simulation (Console)
          files: |
            NEXUS.Fractal-${{ steps.extract-version.outputs.version }}.zip
            NEXUS.Growth-${{ steps.extract-version.outputs.version }}.zip
            NEXUS.Growth.Simulation-${{ steps.extract-version.outputs.version }}.zip