name: NEXUS Release

on:
  push:
    tags:
      - "v*.*.*"
      - "v*.*.*-*"
    paths:
      - 'NEXUS.Fractal/**'
      - 'NEXUS.Growth/**'
      - 'NEXUS.Growth.Simulation/**'
      - '.github/workflows/release.yml'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: windows-latest
    
    steps:
      # ... (все предыдущие шаги остаются без изменений до prepare-release-body)

      - name: Prepare release body
        id: prepare-release-body
        shell: pwsh
        run: |
          # Формируем список приложений
          $appsList = [System.Collections.ArrayList]@()
          if (Test-Path "./NEXUS.Fractal-$env:VERSION.zip") { $appsList.Add("- NEXUS.Fractal (Avalonia)") | Out-Null }
          if (Test-Path "./NEXUS.Growth-$env:VERSION.zip") { $appsList.Add("- NEXUS.Growth (Avalonia)") | Out-Null }
          if (Test-Path "./NEXUS.Simulation-$env:VERSION.zip") { $appsList.Add("- NEXUS.Growth.Simulation (Console)") | Out-Null }
          
          # Получаем хеши
          $hashesContent = Get-Content ./hashes.md5 -Raw
          
          # Формируем тело релиза
          $bodyLines = @(
            "NEXUS Desktop Applications Release $env:VERSION",
            "",
            $appsList -join "`n",
            "",
            "MD5 Hashes:",
            $hashesContent,
            "",
            "Note: Applications are published as full folders (not single-file)"
          )
          
          $body = $bodyLines -join "`n"
          
          # Сохраняем в файл
          $body | Out-File -FilePath "./release_body.md" -Encoding utf8 -NoNewline
          
          # Для вывода в GITHUB_OUTPUT заменяем переносы строк и экранируем кавычки
          $outputBody = $body -replace "`n", "%0A" -replace "`r", "%0D" -replace '"', '\"'
          echo "body=$outputBody" >> $env:GITHUB_OUTPUT

      - name: Create GitHub Release
        id: create-release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          name: NEXUS ${{ env.VERSION }}${{ env.APP && format('-{0}', env.APP) || '' }}
          body_file: release_body.md
          files: |
            ${{ steps.create-archives.outputs.files }}
            hashes.md5