name: NEXUS DESKTOP

on:
  push:
    tags:
      - "v*"  # Запускать workflow при создании тегов, начинающихся с "v" (например, v1.0.0)

permissions:
  contents: write  # Необходимо для создания релизов

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]
    
    runs-on: windows-latest

    env:
      Solution_Name: NEXUS.sln  # Предполагается, что у вас есть solution файл
      Build_Output: build_output

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      # Установка .NET
      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      
      # Создание выходной директории
      - name: Create output directory
        run: mkdir $env:Build_Output
      
      # Сборка Fractal
      - name: Build NEXUS.Fractal
        run: |
          dotnet publish NEXUS.Fractal -c ${{ matrix.configuration }} -r win-x64 --self-contained true -p:PublishSingleFile=true -p:IncludeAllContentForSelfExtract=true -o $env:Build_Output/Fractal
      
      # Сборка Growth
      - name: Build NEXUS.Growth
        run: |
          dotnet publish NEXUS.Growth -c ${{ matrix.configuration }} -r win-x64 --self-contained true -p:PublishSingleFile=true -p:IncludeAllContentForSelfExtract=true -o $env:Build_Output/Growth
      
      # Сборка Growth.Simulation
      - name: Build NEXUS.Growth.Simulation
        run: |
          dotnet publish NEXUS.Growth.Simulation -c ${{ matrix.configuration }} -r win-x64 --self-contained true -p:PublishSingleFile=true -p:IncludeAllContentForSelfExtract=true -o $env:Build_Output/Simulation
      
      # Создание архива с релизом
      - name: Create release zip
        run: |
          $version = $env:GITHUB_REF -replace "refs/tags/v", ""
          Compress-Archive -Path $env:Build_Output/* -DestinationPath NEXUS-$version.zip
      
      # Загрузка артефакта
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: NEXUS-Release
          path: NEXUS-${{ github.ref_name }}.zip

  create-release:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: NEXUS-Release

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: NEXUS ${{ github.ref_name }}
          body: |
            NEXUS Desktop Applications Release
            Includes:
            - NEXUS.Fractal (Avalonia)
            - NEXUS.Growth (Avalonia)
            - NEXUS.Growth.Simulation (Console)
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./NEXUS-${{ github.ref_name }}.zip
          asset_name: NEXUS-${{ github.ref_name }}.zip
          asset_content_type: application/zip